name: Aliyun Signin

on:
  schedule:
   # 每天国际时间 21:20 运行一次, 中国时间 05:20
    - cron: '20 21 * * *'
  workflow_dispatch:
jobs:
  signin:
    name: Aliyun Signin
    runs-on: ubuntu-latest
    steps:
      - uses: ImYrS/aliyun-auto-signin@main
        with:
          REFRESH_TOKENS: ${{ secrets.WREFRESH_TOKENS }},${{ secrets.REFRESH_TOKENS }}
          GP_TOKEN: ${{ secrets.GP_TOKEN}}
          PUSH_TYPES: 'pushplus'
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
